all: QuadraticEquationSolver

QuadraticEquationSolver: src/main.cpp src/QuadEq.cpp src/TestEq.cpp src/QuadEq.h src/TestEq.h
	g++ -Wall -Wextra -O2 -o  QuadraticEquationSolver src/main.cpp src/QuadEq.cpp src/TestEq.cpp

clean:
	rm QuadraticEquationSolver
